[package]
name = "tcge"
version = "0.1.0"
authors = ["Lars Longor K <lalongok@gmail.com>"]

[dependencies]
failure = "0.1.3"
mopa = "0.2.2"
time = "*"
cgmath = "*"
clap = "~2.32.0"

# filesystem
## zip = "0.4.2"
## rust-lzma = "0.2.1"
## notify = "4.0.3"
## filebuffer = "0.4.0"

# graphics
gl = "*"
glfw = "*"
image = "*"
# https://crates.io/keywords/renderdoc

# user interface?
## selectors = "0.19.0"
## rusttype = "0.6.2"
## imgui = "*"

# networking
## mio = "0.6.15"
## ws = "0.7.6"
## rcon = "0.1.0"
## quic = "0.0.3"

# procedural
## simdnoise = "*"

# modding
## https://crates.io/crates/wasmer-runtime/

[build-dependencies]
walkdir = "2.1"
git-version = "0.2.1"

# windres = "0.2.1"
# build_details = "0.1.2"


#cargo extensions?
# - https://crates.io/crates/cargo-modules
# - https://crates.io/crates/cargo-disassemble