[package]
name = "tcge"
version = "0.1.0"
authors = ["Longor1996 <lalongok@gmail.com>"]

[dependencies]
failure = "0.1.3"
time = "*"
cgmath = "*"

# filesystem
## zip = "0.4.2"
## rust-lzma = "0.2.1"
## notify = "4.0.3"
## filebuffer = "0.4.0"

# graphics
gl = "*"
glfw = "*"
image = "*"
# https://crates.io/keywords/renderdoc

# user interface?
## selectors = "0.19.0"
## rusttype = "0.6.2"
## imgui = "*"

# networking
## mio = "0.6.15"
## ws = "0.7.6"
## rcon = "0.1.0"

# procedural
simdnoise = "*"

[build-dependencies]
walkdir = "2.1"
git-version = "0.2.1"

# windres = "0.2.1"
# build_details = "0.1.2"


#cargo extensions?
# - https://crates.io/crates/cargo-modules
# - https://crates.io/crates/cargo-disassemble